version: '3.9'

services:
  mariadb:
    image: mariadb:10.4.28  # Specify the desired MariaDB version
    container_name: mariadb_container
#    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root  # Set the root password
      MARIADB_DATABASE: thesis  # Creates a database named "thesis"
    ports:
      - "3306:3306"  # Maps port 3306 on the container to port 3306 on the host
    volumes:
      # - mariadb_data:/var/lib/mysql  # Persistent storage for database data
      # - mariadb_config:/etc/mysql/conf.d  # Configuration files
      - ./static/data/thesis.sql:/docker-entrypoint-initdb.d/init.sql  # Mount SQL file to run on startup

volumes:
  mariadb_data:
  mariadb_config:
